# Generated by Django 3.1 on 2021-05-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category_name',
            new_name='product_name',
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=True),
        ),
    ]
